#!/usr/bin/env bash
# Build the standalone Windows x64 ADBlock web server with mingw-w64.
# Run inside an MSYS2 MINGW64 shell (see .github/workflows/windows-release.yml).
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE/.."   # repo/webserver

OUT="$HERE/dist"
rm -rf "$OUT"; mkdir -p "$OUT"

echo "==> Embedding Win11 visual-style manifest + application icon ..."
# The icon is generated by CI (Pillow); embed it when present so a plain
# local build still works.
RC_FILE="$HERE/app.rc"
if [ -f "$HERE/app.ico" ]; then
  # windres resolves resources relative to the .rc file, and it is a native
  # Windows binary: an MSYS-style /d/... path would not be found.
  RC_FILE="$HERE/app_build.rc"
  cat "$HERE/app.rc" > "$RC_FILE"
  printf '\n1 ICON "app.ico"\n' >> "$RC_FILE"
fi
windres "$RC_FILE" -O coff -o "$HERE/app_res.o"

echo "==> Compiling webserver.exe ..."
gcc \
  -std=c11 -O2 -Wall -mwindows \
  -fstack-protector-strong \
  -Wl,--dynamicbase,--nxcompat,--high-entropy-va \
  -D MG_ENABLE_IPV6 -DMG_TLS=MG_TLS_OPENSSL -DMG_ENABLE_POLL=1 \
  -I"$HERE" \
  -I"$MINGW_PREFIX/include" \
  -o "$OUT/webserver.exe" \
  jni/webserver.c jni/mongoose/mongoose.c "$HERE/gui_win32.c" "$HERE/update_win32.c" "$HERE/app_res.o" \
  -L"$MINGW_PREFIX/lib" \
  -lssl -lcrypto -lws2_32 -lwinmm -lpthread \
  -lgdi32 -luser32 -lshell32 -ladvapi32 -lcrypt32 -liphlpapi \
  -ldwmapi -luxtheme -lpsapi -lwinhttp -lbcrypt -lwintrust

echo "==> Bundling runtime DLLs ..."
for dll in libssl-3-x64.dll libcrypto-3-x64.dll zlib-1.dll \
           libgcc_s_seh-1.dll libwinpthread-1.dll libssp-0.dll; do
  if [ -f "$MINGW_PREFIX/bin/$dll" ]; then
    cp "$MINGW_PREFIX/bin/$dll" "$OUT/"
  fi
done

# Refuse to publish a binary with a dependency that is not bundled and not a
# Windows system DLL. -fstack-protector-strong adds libssp, and a missing DLL
# is invisible on a CI runner (MSYS2's bin is on PATH there) but makes the
# executable fail to start on a user's machine.
echo "==> Verifying runtime dependencies ..."
missing=""
for dll in $(objdump -p "$OUT/webserver.exe" | sed -n 's/^[[:space:]]*DLL Name:[[:space:]]*//p'); do
  [ -f "$OUT/$dll" ] && continue
  [ -f "/c/Windows/System32/$dll" ] && continue
  missing="$missing $dll"
done
if [ -n "$missing" ]; then
  echo "ERROR: webserver.exe needs DLLs that are neither bundled nor system:"
  echo "      $missing"
  exit 1
fi
echo "==> All imports satisfied ($(objdump -p "$OUT/webserver.exe" | grep -c 'DLL Name:'))"

echo "==> Build output:"
ls -la "$OUT"
echo "==> Done."
